### ISSUE TITLE
await audioService.InitializeAsync(mp) always returns error

### ISSUE THREAD

**Issue by Bob-Varghese** [BeautifulPilgrim/MauiAudio#2]
I am using the code exactly as described in the readme.

private readonly INativeAudioService audioService;

await audioService.InitializeAsync(url);

this line always gives me the same exception: "Object reference not set to an instance of an object."

I confirmed that the url plays the mp3 just fine in the web browser so it is there and available

what am I doing wrong

**Comment by BeautifulPilgrim** [comment]
do you have init the audioService?

**Comment by BeautifulPilgrim** [comment]
Maybe you can refer to this：
`
public class PlayerService
{
    private readonly INativeAudioService audioService;

    public PlayerService(INativeAudioService audioService, WifiOptionsService wifiOptionsService)
    {
        this.audioService = audioService;
    }
    async Task PlayAsync(MediaPlay episode, bool isPlaying, double position = 0){
       ......
            await audioService.InitializeAsync(episode);
       ......
    }
    ...
}
`

**Comment by eylvisaker** [comment]
This suggest does not work on Android. Neither does MauiAudio.Sample.

**Comment by BeautifulPilgrim** [comment]
Hello, I review the code in sample, and fix the bug, and also rewrite the readme. Maybe you can try again. ( But maybe still play slowly, maybe need to wait few seconds, I think there still some bugs to fix.)

**Comment by iascience** [comment]
I had this exact problem on Android, then realised I hadn't added the initialization code in MainActivity. By the way, the ReadMe for Android says "MainApplication.cs" for this initialisation code, when I 'm pretty sure it means "MainActivity.cs".

**Comment by BeautifulPilgrim** [comment]
ok, thank you @iascience. I have change the ReadMe.
